#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re, os, glob

BASE = os.path.dirname(os.path.abspath(__file__))

T = {
    "convolutional networks": ["摺積網路"],
    "convolutional network": ["摺積網路"],
    "convolutional layers": ["摺積層"],
    "recurrent layers": ["遞迴層"],
    "deep convolutional network": ["深度摺積網路"],
    "deep convolutional networks": ["深度摺積網路"],
    "deep convolutional neural network architecture": ["深度摺積神經網路架構"],
    "convolutional neural networks": ["摺積神經網路"],
    "convolutional neural network": ["摺積神經網路"],
    "deep classification networks": ["深度分類網路"],
    "deep neural networks": ["深度神經網路"],
    "deep neural network": ["深度神經網路"],
    "deep learning": ["深度學習"],
    "deep learning approaches": ["深度學習方法"],
    "recurrent neural networks": ["遞迴神經網路"],
    "recurrent neural network": ["遞迴神經網路"],
    "neural networks": ["神經網路"],
    "neural network": ["神經網路"],
    "fully connected layers": ["全連接層"],
    "semantic segmentation": ["語義分割"],
    "object detection": ["物件偵測"],
    "receptive fields": ["感受野"],
    "deconvolution": ["反摺積"],
    "skip connections": ["跳躍連接"],
    "skip architecture": ["跳躍架構"],
    "conditional random fields (crfs)": ["條件隨機場（CRF）"],
    "bottom-up recognition": ["由下而上的辨識"],
    "top-down refinement": ["由上而下的精化"],
    "bounding box object detection": ["邊界框物件偵測"],
    "part and keypoint prediction": ["部件與關鍵點預測"],
    "local correspondence": ["局部對應關係"],
    "dropout": ["Dropout"],
    "supervised pre-training": ["監督式預訓練"],
    "stochastic gradient descent": ["隨機梯度下降"],
    "attention mechanisms": ["注意力機制"],
    "deeper recurrent architectures": ["更深的遞迴架構"],
    "fully convolutional network": ["全摺積網路"],
    "fully convolutional networks": ["全摺積網路"],
    "fully convolutional network (fcn)": ["全摺積網路（FCN）"],
    "fully convolutional training and prediction": ["全摺積的訓練與預測"],
    "fcn-32s": ["FCN-32s"],
    "fcn-16s": ["FCN-16s"],
    "fcn-8s": ["FCN-8s"],
    "inception": ["Inception"],
    "inception module": ["Inception 模組"],
    "googlenet architecture": ["GoogLeNet 架構"],
    "lenet-5": ["LeNet-5"],
    "network in network": ["Network in Network"],
    "arora et al.": ["Arora 等人"],
    "inception architecture": ["Inception 架構"],
    "face recognition": ["人臉辨識"],
    "facenet": ["FaceNet"],
    "euclidean embedding": ["歐氏嵌入"],
    "triplet loss": ["三元組損失"],
    "triplet mining method": ["三元組挖掘方法"],
    "triplet-based loss function": ["基於三元組的損失函數"],
    "hard triplets": ["困難三元組"],
    "deepface": ["DeepFace"],
    "deepid": ["DeepID"],
    "online triplet mining strategy": ["線上三元組挖掘策略"],
    "triplet loss function": ["三元組損失函數"],
    "d-dimensional hypersphere": ["d 維超球面"],
    "artificial intelligence": ["人工智慧"],
    "computer vision": ["電腦視覺"],
    "natural language processing": ["自然語言處理"],
    "generative model": ["生成模型"],
    "machine translation": ["機器翻譯"],
    "neural machine translation": ["神經機器翻譯"],
    "sequence-to-sequence models": ["序列到序列模型"],
    "visual content": ["視覺內容"],
    "generation-based methods": ["生成方法"],
    "hidden state": ["隱藏狀態"],
    "beam search": ["束搜尋"],
    "long-term recurrent convolutional networks (lrcns)": ["長期遞迴摺積網路（LRCN）"],
    "lrcn architecture": ["LRCN 架構"],
    "visual recognition": ["視覺辨識"],
    "sequential tasks": ["序列任務"],
    "activity recognition": ["動作辨識"],
    "image description": ["影像描述"],
    "video description": ["影片描述"],
    "image and video description": ["影像與影片描述"],
    "neural generation approaches": ["神經生成方法"],
    "two-stream networks": ["雙流網路"],
    "two-stream approach": ["雙流方法"],
    "3d convolutional networks": ["三維摺積網路"],
    "encoder-decoder paradigm in neural machine translation": ["神經機器翻譯中的編碼器-解碼器範式"],
    "convolutional deep belief network": ["摺積深度信念網路"],
    "convolutional deep belief networks": ["摺積深度信念網路"],
}

print('Term table loaded:', len(T), 'entries')
